- id: '1592138061839'
  alias: Fix cold mornings
  description: ''
  trigger:
  - at: 07:00
    platform: time
  condition:
  - below: '10'
    condition: numeric_state
    entity_id: sensor.bom_melbourne_air_temp_c
  action:
  - data: {}
    entity_id: switch.60013016c44f33b3eadd
    service: switch.turn_on
  - delay: 0:15
  - data: {}
    entity_id: switch.60013016c44f33b3eadd
    service: switch.turn_off
