# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
homeassistant:
  customize: !include customize.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


history:
  exclude:
    entity_globs:
     - sensor.oneplus_*
     - sensor.faxy_s_phone*
     - binary_sensor.oneplus_*
     - binary_sensor.faxy_s_phone*
     - person.faxy
     - device_tracker*
recorder:

frontend:
  themes: !include_dir_merge_named themes

media_player:
  - platform: epson
    host: 192.168.1.9

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    interval_seconds: 30
    consider_home: 360
    new_device_defaults:
      track_new_devices: false

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: "61"

shopping_list:
weather:
  !include weather.yaml
sensor:
  !include sensors.yaml
discovery:
  ignore:
  enable:
