# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
homeassistant:
  customize: !include customize.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


history:
  exclude:
    entity_globs:
     - sensor.oneplus_*
     - sensor.faxy_s_phone*
     - binary_sensor.oneplus_*
     - binary_sensor.faxy_s_phone*
     - person.faxy
     - device_tracker*
recorder:

input_select:
  last_ac_scene:
    name: Last AC before powercycle
    options:
      - Heat
      - Cool
      - Dry
      - Fan
  ac_scene:
    name: AC Mode
    options:
      - Heat
      - Cool
      - Dry
      - Fan
      - "Off"
  ac_on:
    name: AC power
    options:
      - On
      - Off

frontend:
  themes: !include_dir_merge_named themes

media_player:
  - platform: epson
    host: 192.168.1.9

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    interval_seconds: 30
    consider_home: 360
    new_device_defaults:
      track_new_devices: false

switch:
  - platform: template
    switches:
      aircon_cool:
        value_template: '{{is_state("input_select.ac_scene", "Cool") and is_state("climate.44054805840d8ea4bd2a", "auto")}}'
        turn_on:
          service: script.ac_cool
        turn_off:
          service: climate.set_hvac_mode
          data:
            entity_id: climate.44054805840d8ea4bd2a
            hvac_mode: 'off'
      aircon_heat:
        value_template: '{{is_state("input_select.ac_scene", "Heat") and is_state("climate.44054805840d8ea4bd2a", "auto")}}'
        turn_on:
          service: script.ac_heat
        turn_off:
          service: climate.set_hvac_mode
          data:
            entity_id: climate.44054805840d8ea4bd2a
            hvac_mode: 'off'
      aircon_dry:
        value_template: '{{is_state("input_select.ac_scene", "Dry" and is_state("climate.44054805840d8ea4bd2a", "auto"))}}'
        turn_on:
          service: script.ac_dry
        turn_off:
          service: climate.set_hvac_mode
          data:
            entity_id: climate.44054805840d8ea4bd2a
            hvac_mode: 'off'
      aircon_power:
        value_template: '{{is_state("climate.44054805840d8ea4bd2a", "auto")}}'
        turn_on:
          service: climate.set_hvac_mode
          data:
            entity_id: climate.44054805840d8ea4bd2a
            hvac_mode: 'auto'
        turn_off:
          service: climate.set_hvac_mode
          data:
            entity_id: climate.44054805840d8ea4bd2a
            hvac_mode: 'off'

climate:
  - platform: dualmode_generic
    name: Faxys room
    heater: scene.pxbahpx0p8jgz5rg
    cooler: scene.u3hzqmwwvldx0nq5
    target_sensor: sensor.faxy_s_room_temperature

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: "61"

shopping_list:
weather:
  !include weather.yaml
sensor:
  !include sensors.yaml
discovery:
  ignore:
  enable:
